apiVersion: v1
kind: Service
metadata:
  name: frontend-canary-service
  labels:
    app: frontend
    tier: web
    track: canary
spec:
  selector:
    app: frontend
    track: canary
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
